name: Deploy App

on:
  push:
    branches:
      - master  # Adjust if using a different branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set Git user
        run: |
          git config --global user.email "tannerowens10@gmail.com"
          git config --global user.name "ParagonTeo"

      - name: Set OpenAI API key environment variable
        run: echo "REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }}" >> $GITHUB_ENV


      - name: Deploy application
        run: |
          npm run build
          npx gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
